In [1]:
pip install pandas

Collecting pandas
  Using cached pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
Collecting pytz>=2020.1
  Using cached pytz-2026.2-py2.py3-none-any.whl (510 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./model_env/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Collecting numpy>=1.22.4
  Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
Collecting tzdata>=2022.7
  Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Requirement already satisfied: six>=1.5 in ./model_env/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.3.3 pytz-2026.2 tzdata-2026.2
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/talahanuman/dev/projects/Faang/backend/Model/model_env/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

In [8]:
data = pd.read_excel('model_data.xlsx')

In [7]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Collecting et-xmlfile
  Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/talahanuman/dev/projects/Faang/backend/Model/model_env/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [9]:
data.head()

,LeetCode_Rating,LC_Easy,LC_Medium,LC_Hard,System_Design_Score,Github_Dev_Score,Internship_Score,Target_Probability_Score
0,1673,148,134,40,1,96,2,0.5832
1,1451,342,116,52,1,89,3,0.5986
2,1726,123,148,42,1,52,2,0.4185
3,2033,122,181,48,0,44,1,0.3885
4,1418,330,111,44,1,93,2,0.6391

In [8]:
data.drop('Candidate_ID', axis=1, inplace=True)

In [9]:
data.head()

,LeetCode_Rating,LC_Easy,LC_Medium,LC_Hard,System_Design_Score,Github_Dev_Score,Internship_Domain,Internship_Score,Target_Probability_Score
0,1673,148,134,40,1,96,Fullstack,2,0.5832
1,1451,342,116,52,1,89,Backend/Cloud,3,0.5986
2,1726,123,148,42,1,52,Fullstack,2,0.4185
3,2033,122,181,48,0,44,Frontend,1,0.3885
4,1418,330,111,44,1,93,Fullstack,2,0.6391

In [11]:
data.drop('Internship_Domain', axis=1, inplace=True)

In [11]:
pip install sklearn

Collecting sklearn
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/talahanuman/dev/projects/Faang/backend/Model/model_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_2e4b889273be45c287b3c438e0763a58/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_2e4b889273be45c287b3c438e0763a58/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-pip-egg-info-b_e6c3o8
         cwd: /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_2e4b889273be45c287b3c438e0763a58/
    Complete output (15 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/46/1c/395a83ee7b2d2ad7a05b453872053d41449564477c81dc356f720b16eac4/sklearn-0.0.post12.tar.gz#sha256=54cff9e20839b7b202321178228af4d9388bedf78425d9299fd9ee170d68802e (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached sklearn-0.0.post11.tar.gz (3.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/talahanuman/dev/projects/Faang/backend/Model/model_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_2788d912901c49929061a17c15bc3cb6/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_2788d912901c49929061a17c15bc3cb6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-pip-egg-info-_06ctelx
         cwd: /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_2788d912901c49929061a17c15bc3cb6/
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a4/0b/d1c703256cf293be77b7db44dbef62251fe02a97d0bef981f7120b0b0c0f/sklearn-0.0.post11.tar.gz#sha256=af035c4f0b970b7fc2d3856079aa1aa1032df3d7f65048a9d87114abf13c4629 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached sklearn-0.0.post10.tar.gz (3.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/talahanuman/dev/projects/Faang/backend/Model/model_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_ec297ebab6354d6fb50baab4482c46d0/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_ec297ebab6354d6fb50baab4482c46d0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-pip-egg-info-0gp9a2nd
         cwd: /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_ec297ebab6354d6fb50baab4482c46d0/
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b9/0e/b2a4cfaa9e12b9ca4c71507bc26d2c99d75de172c0088c9835a98cf146ff/sklearn-0.0.post10.tar.gz#sha256=d4cd5a2e64b3caaf82cd5e33c46884dfeec5ebf991710d9faeb4fe81cadb3ba6 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached sklearn-0.0.post9.tar.gz (3.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/talahanuman/dev/projects/Faang/backend/Model/model_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_e7137c9088db4ca99fa9de4ca9dd0556/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_e7137c9088db4ca99fa9de4ca9dd0556/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-pip-egg-info-j7hx4nmf
         cwd: /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_e7137c9088db4ca99fa9de4ca9dd0556/
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/28/86/207a003339023247fef1bb5bc9f5093140d17294b2f6d15bfcd4885e469e/sklearn-0.0.post9.tar.gz#sha256=1ff5864cf30489ee48a014fe8f4320d7bb59592392a4ef52ae9d7a37942615ac (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached sklearn-0.0.post7.tar.gz (3.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/talahanuman/dev/projects/Faang/backend/Model/model_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_bd4486feb6174078b6ad0b6e98aeba2c/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_bd4486feb6174078b6ad0b6e98aeba2c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-pip-egg-info-84dbwmt1
         cwd: /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_bd4486feb6174078b6ad0b6e98aeba2c/
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/70/ce/81aa643f3c43488c4a1e417e45f696a61e7ac82b57190fad3c310df2c07b/sklearn-0.0.post7.tar.gz#sha256=1c89020b364fdc3aa2839e0ae34e8f0b406669e4b5c2359dda3ac398f9c76874 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached sklearn-0.0.post5.tar.gz (3.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/talahanuman/dev/projects/Faang/backend/Model/model_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_8149399ec60d4e0ba05da21adf582a14/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_8149399ec60d4e0ba05da21adf582a14/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-pip-egg-info-kbvcfkv0
         cwd: /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_8149399ec60d4e0ba05da21adf582a14/
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7a/93/e0e1b1e98f39dfca7ec9795cb46f6e09e88a2fd5d4a28e4b3d1f618a2aec/sklearn-0.0.post5.tar.gz#sha256=7377c714a03a79bbe9196f435db931fd2a6fa8c68514da7ed3a251fd08c52e2c (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached sklearn-0.0.post4.tar.gz (3.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/talahanuman/dev/projects/Faang/backend/Model/model_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_54948b9fa1124c238b4e22b0f7c72591/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_54948b9fa1124c238b4e22b0f7c72591/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-pip-egg-info-zr2tji51
         cwd: /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_54948b9fa1124c238b4e22b0f7c72591/
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/99/b2/165110013aa66fae6fc13918ad0e9de4801e5f1691d371bf8b63328037e6/sklearn-0.0.post4.tar.gz#sha256=0e81ec9c32d4bb418e7be8f1ec1027d174975502dc84cbc4f4564b4cba31e674 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached sklearn-0.0.post1.tar.gz (3.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/talahanuman/dev/projects/Faang/backend/Model/model_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_b486fca3c8aa4ab9a556e66a045a9563/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_b486fca3c8aa4ab9a556e66a045a9563/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-pip-egg-info-ns4dlfvt
         cwd: /private/var/folders/c5/rqlzzkr91w7cz38_n_ddyk600000gn/T/pip-install-bp0azz0t/sklearn_b486fca3c8aa4ab9a556e66a045a9563/
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/db/1e/af4e9cded5093a92e60d4ae7149a02c7427661b2db66c8ea4d34b17864a2/sklearn-0.0.post1.tar.gz#sha256=76b9ed1623775168657b86b5fe966d45752e5c87f528de6240c38923b94147c5 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached sklearn-0.0.tar.gz (1.1 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.6.1-cp39-cp39-macosx_12_0_arm64.whl (11.1 MB)
Collecting threadpoolctl>=3.1.0
  Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Collecting joblib>=1.2.0
  Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Requirement already satisfied: numpy>=1.19.5 in ./model_env/lib/python3.9/site-packages (from scikit-learn->sklearn) (2.0.2)
Collecting scipy>=1.6.0

In [19]:
x = data.drop('Target_Probability_Score', axis=1)
y = data['Target_Probability_Score']
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [21]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((2000, 7), (2000,), (500, 7), (500,))

In [22]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

Mean Squared Error: 0.0032451689103082854
R^2 Score: 0.7566012810416849

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_squared_error

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Bagging": BaggingRegressor(random_state=42),
    "KNN": KNeighborsRegressor()
}

for name, model in models.items():
    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)

    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)

    print(f"\n{name}")
    print(f"R²  : {r2:.4f}")
    print(f"MSE : {mse:.6f}")

NameError: name 'x_train' is not defined

In [24]:
from sklearn.linear_model import Ridge, Lasso
models = {
    "Linear Regression": LinearRegression(),
    "Ridge": Ridge(alpha = 1.0),
    "Lasso": Lasso(alpha = 0.01)
}
for name, model in models.items():
    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)

    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)

    print(f"\n{name}")
    print(f"R²  : {r2:.4f}")
    print(f"MSE : {mse:.6f}")

Linear Regression
R²  : 0.7566
MSE : 0.003245

Ridge
R²  : 0.7566
MSE : 0.003245

Lasso
R²  : 0.7513
MSE : 0.003315

In [41]:
# liner regerrssion is winner 
data.to_excel("model_data.xlsx", index=False)
x = data.drop('Target_Probability_Score', axis=1)
y = data['Target_Probability_Score']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = LinearRegression()
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)
model.fit(x_train, y_train)

(2000, 7) (500, 7) (2000,) (500,)

LinearRegression()

In [42]:
y_pred = model.predict(x_test)
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

Mean Squared Error: 0.0032451689103082854
R^2 Score: 0.7566012810416849

In [6]:
data.max()

LeetCode_Rating             2848.0000
LC_Easy                      449.0000
LC_Medium                    245.0000
LC_Hard                       89.0000
System_Design_Score            3.0000
Github_Dev_Score             100.0000
Internship_Score               4.0000
Target_Probability_Score       0.8501
dtype: float64

In [35]:
import joblib
joblib.dump(model, 'linear_regression_model.pkl')

['linear_regression_model.pkl']

In [50]:
model.predict([[0, 0, 0, 0, 1, 0, 4]])

/Users/talahanuman/dev/projects/Faang/backend/Model/model_env/lib/python3.9/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([0.18749642])

LeetCode_Rating	LC_Easy	LC_Medium	LC_Hard	System_Design_Score	Github_Dev_Score	Internship_Domain	Internship_Score	Target_Probability_Score

the pattern